### ISSUE TITLE
Dev NumbersFoldedRoleTest

### ISSUE THREAD

**Issue by altitdb** [altitdb/bolaodamega#12]

**Comment by ghost** [comment]
game.setNumber01(1);
game.setNumber02(2);
game.setNumber03(3);
game.setNumber04(4);
game.setNumber05(5);
game.setNumber06(11);

this game should be false right? 
after all 1 and 2  counts as folded numbers and 3 and 4 also count.
In my point of view we got two folded numbers here.

**Comment by altitdb** [comment]
You're right. It's possible have more than one folded number. You can remove some game when exists foldeds.
